
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author user
 */
public class EditPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditPanel
     */
    public EditPanel() {
        initComponents();
        entryIsActive(false);
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkButtonGroup = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nimTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        lakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        umurSpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        provComboBox = new javax.swing.JComboBox<>();
        updateToggleButton = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        kabComboBox = new javax.swing.JComboBox<>();
        hapusToggleButton = new javax.swing.JToggleButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        cariTextField = new javax.swing.JTextField();
        cariButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mahasiswaTable = new javax.swing.JTable();
        footer = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(102, 102, 102)));

        jLabel1.setText("NIM");

        jLabel2.setText("NAMA");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Edit Data");

        nimTextField.setEditable(false);

        jkButtonGroup.add(lakiRadioButton);
        lakiRadioButton.setText("Laki-laki");

        jkButtonGroup.add(perempuanRadioButton);
        perempuanRadioButton.setText("Perempuan");

        jLabel5.setText("Umur");

        umurSpinner.setModel(new javax.swing.SpinnerNumberModel(15, 15, null, 1));
        umurSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(umurSpinner, ""));

        jLabel6.setText("tahun");

        jLabel7.setText("Provinsi");

        provComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jawa Timur", "Jawa Tengah", "DI Yogyakarta", "Jawa Barat", "DKI Jakarta", "Banten" }));
        provComboBox.setSelectedItem("");

        updateToggleButton.setText("Update");
        updateToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateToggleButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Kabupaten");

        kabComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banyuwangi", "Surabaya", "Bandung", "Surakarta" }));
        kabComboBox.setSelectedItem("");

        hapusToggleButton.setText("Hapus");
        hapusToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lakiRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(perempuanRadioButton))
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(umurSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(provComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kabComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(updateToggleButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hapusToggleButton))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel4)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lakiRadioButton)
                    .addComponent(perempuanRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(umurSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(provComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(kabComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateToggleButton)
                    .addComponent(hapusToggleButton))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel9.setMaximumSize(new java.awt.Dimension(460, 2147483647));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Data Tersimpan");
        jPanel5.add(jLabel10);

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));
        jPanel10.add(cariTextField);

        cariButton.setText("Cari");
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });
        jPanel10.add(cariButton);

        jPanel2.add(jPanel10, java.awt.BorderLayout.PAGE_END);

        jPanel9.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        mahasiswaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Jenis Kelamin", "Provinsi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mahasiswaTable.getTableHeader().setReorderingAllowed(false);
        mahasiswaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mahasiswaTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(mahasiswaTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel9, java.awt.BorderLayout.CENTER);

        footer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel9.setText("By Gestyan Ramadhan");
        footer.add(jLabel9);

        jPanel3.add(footer, java.awt.BorderLayout.PAGE_END);

        add(jPanel3, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void updateToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateToggleButtonActionPerformed
        // TODO add your handling code here:
        Mahasiswa mhs = new Mahasiswa();
        ValidasiMahasiswa vldMhs = new ValidasiMahasiswa();
        Database dataMahasiswa = Database.getInstance();
        mhs.setNim(nimTextField.getText());
        mhs.setName(nameTextField.getText());
        int umur = (Integer) umurSpinner.getValue();
        mhs.setUmur(umur);
        if (lakiRadioButton.isSelected()) {
            mhs.setJk("Laki-laki");
        } else if (perempuanRadioButton.isSelected()) {
            mhs.setJk("Perempuan");
        } else {
            mhs.setJk("");
        }
        mhs.setProv(provComboBox.getSelectedItem().toString());
        mhs.setKab(kabComboBox.getSelectedItem().toString());
        if (vldMhs.getIsTrueEdit(mhs)) {
            JOptionPane.showMessageDialog(this, vldMhs.getMessage());
            clearForm();
            dataMahasiswa.updateMahasiswa(mhs);
            loadTableData();
        } else {
            JOptionPane.showMessageDialog(this, vldMhs.getMessage());
        }
        clearForm();
        entryIsActive(false);
    }//GEN-LAST:event_updateToggleButtonActionPerformed

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
        // TODO add your handling code here:
        final String ERROR_NOT_FOUND = "Nim tidak ditemukan\n.";
        final String ERROR_KEY_NOT_ENTRY = "Masukkan Nim";
        final String ERROR_NOT_NIM = "Untuk sementara,\npencarian hanya dapat dilakukan dengan NIM.\n Harap memasukkan NIM dengan benar.";
        Boolean isNumber = true;
        clearForm();
        entryIsActive(false);
        Database dataMhs = Database.getInstance();
        Mahasiswa mhs = null;
        String nimCari = cariTextField.getText();
        System.out.println(nimCari);
        DefaultTableModel dtm = (DefaultTableModel) mahasiswaTable.getModel();

        if (!nimCari.equals("")) {
            for (int i = 0; i < nimCari.length(); i++) {
                if (!Character.isDigit(nimCari.charAt(i))) {
                    isNumber = false;
                    break;
                }
            }
            if (isNumber) {
//                System.out.println(nimCari);
                mhs = dataMhs.getMahasiswa(nimCari);
                if (mhs != null) {
                    while (dtm.getRowCount() > 0) {
                        dtm.removeRow(0);
                    }
                    entryIsActive(true);
                    dtm.addRow(new Object[]{
                        mhs.getNim(),
                        mhs.getName(),
                        mhs.getJk(),
                        mhs.getProv()});
                    nimTextField.setText(mhs.getNim());
                    nameTextField.setText(mhs.getName());
                    if (mhs.getJk().equals("Laki-laki")) {
                        lakiRadioButton.setSelected(true);
                    } else {
                        perempuanRadioButton.setSelected(true);
                    }
                    umurSpinner.setValue(mhs.getUmur());
                    provComboBox.setSelectedItem(mhs.getProv());
                    kabComboBox.setSelectedItem(mhs.getKab());
                } else {
                    JOptionPane.showMessageDialog(this, ERROR_NOT_FOUND);
                    
                    loadTableData();
                }
            } else {
                JOptionPane.showMessageDialog(this, ERROR_NOT_NIM);
                loadTableData();
            }
        } else {
            JOptionPane.showMessageDialog(this, ERROR_KEY_NOT_ENTRY);
            loadTableData();
        }
    }//GEN-LAST:event_cariButtonActionPerformed

    private void mahasiswaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mahasiswaTableMouseClicked
        // TODO add your handling code here:
        Mahasiswa m = null;
        Database dataMhs = Database.getInstance();
        int row = mahasiswaTable.getSelectedRow();
        entryIsActive(true);

        m = dataMhs.getMahasiswa(mahasiswaTable.getValueAt(row, 0).toString());
        nimTextField.setText(m.getNim());
        nameTextField.setText(m.getName());
        if (m.getJk().equals("Laki-laki")) {
            lakiRadioButton.setSelected(true);
        } else {
            perempuanRadioButton.setSelected(true);
        }
        umurSpinner.setValue(m.getUmur());
        provComboBox.setSelectedItem(m.getProv());
        kabComboBox.setSelectedItem(m.getKab());
    }//GEN-LAST:event_mahasiswaTableMouseClicked

    private void hapusToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusToggleButtonActionPerformed
        // TODO add your handling code here:
        Mahasiswa m = null;
        Database dataMahasiswa = Database.getInstance();
        if (JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus?") == JOptionPane.OK_OPTION) {
            dataMahasiswa.delMahasiswa(nimTextField.getText());
            loadTableData();
            entryIsActive(false);
            clearForm();
        }
    }//GEN-LAST:event_hapusToggleButtonActionPerformed
    private void clearForm() {
        nimTextField.setText("");
        nameTextField.setText("");
        jkButtonGroup.clearSelection();
        umurSpinner.setValue(15);
        provComboBox.setSelectedIndex(0);
        kabComboBox.setSelectedIndex(0);
    }

    private void loadTableData() {
        DefaultTableModel dtm = (DefaultTableModel) mahasiswaTable.getModel();
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        try {
            for (Mahasiswa mhs : Database.getInstance().getListMahasiswa()) {
                dtm.addRow(new Object[]{
                    mhs.getNim(),
                    mhs.getName(),
                    mhs.getJk(),
                    mhs.getProv()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(EditPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void entryIsActive(Boolean bool) {
        nameTextField.setEditable(bool);
        lakiRadioButton.setEnabled(bool);
        perempuanRadioButton.setEnabled(bool);
        umurSpinner.setEnabled(bool);
        provComboBox.setEnabled(bool);
        kabComboBox.setEnabled(bool);
        updateToggleButton.setEnabled(bool);
        hapusToggleButton.setEnabled(bool);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariButton;
    private javax.swing.JTextField cariTextField;
    private javax.swing.JPanel footer;
    private javax.swing.JToggleButton hapusToggleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup jkButtonGroup;
    private javax.swing.JComboBox<String> kabComboBox;
    private javax.swing.JRadioButton lakiRadioButton;
    private javax.swing.JTable mahasiswaTable;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JComboBox<String> provComboBox;
    private javax.swing.JSpinner umurSpinner;
    private javax.swing.JToggleButton updateToggleButton;
    // End of variables declaration//GEN-END:variables
}
